# This is a basic workflow to help you get started with Actions

name: Build_DS3615_Bootloader

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: edit ds918 config
        env:
          DS3615_PID: ${{ secrets.DS3615_PID_new }}
          DS3615_VID: ${{ secrets.DS3615_VID_new }}
          DS3615_SN: ${{ secrets.DS3615_SN_new}}
          DS3615_MAC: ${{ secrets.DS3615_MAC_new}}
        run: |
          chmod +x rp-helper.sh
          sed -i "s/1234XXX123/${DS3615_SN}/g" apollolake_user_config.json
          sed -i "s/XXYYXXYYXXYY/${DS3615_MAC}/g" apollolake_user_config.json
          sed -i "s/0x46f4/${DS3615_VID}/g" apollolake_user_config.json
          sed -i "s/0x0001/${DS3615_PID}/g" apollolake_user_config.json

      - name: build ds918 7.0.1
        run: |
          ./rp-helper.sh build apollolake-7.0.1-42218

      - name: create ds918 7.0.1 image
        run: |
          ./rp-helper.sh auto apollolake-7.0.1-42218

      - uses: actions/upload-artifact@v2
        with:
          name: images
          path: images/*.img
